### PR TITLE
Added language Bengali language support

### PR DESCRIPTION
**Pull request by mmsami**
Hi, added the first version of Bengali language translations (code: Bn) to the project from my understanding.

### CODE REVIEW

**Review by jmechnich — CHANGES_REQUESTED** [review]
Please remove all .DS_Store files from your pull request. Those are metadata files created by macOS that should not be part of the code.

**Comment by mmsami** [comment]
Thank you so much. I forgot about that. I deleted the .DS_Store files. Do I need to create a pull request again?

**Review by stweil — APPROVED** [review]
Thank you!

**Review by jmechnich — COMMENTED** [review]
That looked ok, just closing this for me.

**Pull request merged**
