### PR TITLE
 added some arabic translations in a new folder

### PR DESCRIPTION
**Pull request by mahmoudHussein**
added some of the arabic translations in a new folder :)

### CODE REVIEW

**Comment by stweil** [comment]
Thanks for this contribution. Could you please check these issues and send an updated pull request:

* locale/ar_US.UTF-8 would be Arabic language as it is spoken in the United States, encoded in UTF-8. Obviously "US" should be replaced. See https://en.wikipedia.org/wiki/ISO_3166-2 for potential country codes.

* All commit messages for PalMA should be signed: they must end with a separate line and your signature. Here is an example with my signature: https://github.com/UB-Mannheim/PalMA/commit/6422785ef5bc00a45b1d2612b9134a7fec5be607

* The header of  locale/ar_US.UTF-8/LC_MESSAGES/palma.po needs some adjustments like language (not English), name of author (not Stefan Weil).

**Comment by zuphilip** [comment]
I am working to integrate your Arabic translation into PalMA.

<blockquote>locale/ar_US.UTF-8 would be Arabic language as it is spoken in the United States, encoded in UTF-8. Obviously "US" should be replaced. </blockquote>

I guess we should start with the "standard Arabic" language. However, I couldn't come up with any country for the "standard". Therefore, I think `locale/ar_US` may be not that bad. What do you think?

(CC @mahmoudHussein)

**Comment by stweil** [comment]
There seems to be some kind of standard (https://en.wikipedia.org/wiki/Modern_Standard_Arabic). We could simply use `locale/ar` as the base directory.

**Comment by stweil** [comment]
@mahmoudHussein, it would be a pity if your work would have been for nothing. Therefore we are planning to add your contribution to PalMA even if it is not signed.

**Comment by mahmoudHussein** [comment]
Dear stefan,
Good afternoon!  Sorry i have been out of the country and just came back to
all my emails, thats is why i want to apologise for the late reply. As for
the arabic naming i saw on an earlier mail we could use the directory
"local/ar" as suggested. Should i add it ?!

Best regards,
Mahmoud Osman

**Comment by stweil** [comment]
Hello Mahmoud,

no need for you to fix the directory - that's something which can be easily done on our side. Would it be fine for you if I add a line "Signed-off-by: Mahmoud Osman <...>" (... = your e-mail address) to the commit message?

Kind regards,
Stefan

**Comment by mahmoudHussein** [comment]
Hello Stefan,
Yes sure you can add it. Incase you don't know my email its "mosman. If
anything more is needed just let me know.

Best regards,
Mahmoud Osman

**Comment by stweil** [comment]
@mahmoudHussein, so I should use your Mannheim email address instead of the gmail address for your commit?

**Comment by mahmoudHussein** [comment]
Hi Stefan,
If you can use my gmail address actually it is preferable. Thanks so much.
Best Regards,
Mahmoud Osman

**Comment by stweil** [comment]
The modification was applied to git master now (commit 7fb740934338a17a775a83d1ef720ce0335b0ad0), thank you very much.

**Pull request closed without merging**
