### PR TITLE
Update ru_RU translation

### PR DESCRIPTION
**Pull request by kba**
This combines #34 and #35 and adds the `Signed-off`.

@aleksandrairt Let us know if that is okay for you. @stweil can then merge it.

### CODE REVIEW

**Comment by stweil** [comment]
@kba, a Signed-off-by must use the real name (I assume that aleksandrairt is not the real name).

**Comment by kba** [comment]
@stweil I did not want to deanonmyze and it's not easy to explain what `Signed-off` means. I haven't seen it used outside the Linux kernel. Maybe you could add a sentence to https://github.com/UB-Mannheim/PalMA#contributing to explain why it's purpose and talk to @aleksandrairt directly. I can rebase/force-push the changes then.

**Comment by stweil** [comment]
@kba, I merged the single commits from @aleksandrairt with some updates for the commit message after talking to her. Thanks to both of you.

**Comment by kba** [comment]
I think this just merges only one of the three commits by @aleksandrairt. Missing:
*  https://github.com/UB-Mannheim/PalMA/pull/34/commits/950676cb13cbba523ba924bc18ad5fa2f3ad129a
* https://github.com/UB-Mannheim/PalMA/pull/34/commits/8c5f43a66b222ad0d3b5cb7e48cb01368af36469

**Comment by stweil** [comment]
I added three commits, but they got new identifiers because of the mentioned modifications in the commit message. So hopefully I got all updates.

**Comment by kba** [comment]
Yes, you did, I realized that after commenting, sorry. Russian translation is now more complete than German :smile: 

```
$ /docs/dist/find-untranslated.pl |sort -rnk2
zh_CN   100.00%  (64 / 64)
ru_RU   98.44%   (63 / 64)
de_DE   96.88%   (62 / 64)
it_IT   93.75%   (60 / 64)
al_AL   93.75%   (60 / 64)
es_ES   92.19%   (59 / 64)
ar      42.19%   (27 / 64)
ur_PK   20.31%   (13 / 64)
```

**Pull request closed without merging**
