### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by zuphilip** [comment]
Did you also run
```
docs/dist/find-untranslated.pl --markdown
```
to update [`TRANSLATIONS.md`](https://github.com/UB-Mannheim/PalMA/blob/master/TRANSLATIONS.md)? Is it unchanged?

**Comment by stweil** [comment]
I did not run it. There are a few new strings (3?), but I expect more changes (for example replacing RealVNC) and also some fixes, so I just decided to wait with that update.

**Comment by zuphilip** [comment]
Okay. BTW I suggest to move the TRANSLATIONS.md file into the subfolder `locale` and rename it there to README.md in order to be directly rendered in GitHub.

**Comment by stweil** [comment]
> I suggest to move the TRANSLATIONS.md file into the subfolder locale and rename it there to README.md

That's a good idea. I added some commits which implement that (and updated the file for this, too).

**Pull request merged**
