### PR TITLE
Hindi Devanagari script translation added

### PR DESCRIPTION
**Pull request by ashishrana160796**
Thank you, for reviewing the PR! I hope this contribution is helpful.

### CODE REVIEW

**Review by stweil — APPROVED** [review]
Thank you for that great contribution!

**Comment by stweil** [comment]
@ashishrana160796, you used two different e-mail addresses in your commits. Which of them should I use if I combine your commits into a single commit, gmail or university? It will be part of the git history "forever".

I think that instead of `hi_HI`, `hi_IN` would be the right name. See https://lh.2xlibre.net/locale/hi_IN/ for example.
Either fix that by an additional commit, or I can fix it when merging your pull request.

**Comment by ashishrana160796** [comment]
Hello @stweil, thanks for the inputs regarding the PR! I have made the suggested `hi_HI` to `hi_IN` change, and I hope this work well with the PR. Also, please do add the university email only in the commit history. Thank you!

**Comment by stweil** [comment]
Done. Thanks again and good luck.

**Pull request merged**
