### PR TITLE
Signed-off-by: bbbbtong <btong@mail.uni-mannheim.de>

### PR DESCRIPTION
**Pull request by bbbbtong**
Change something in zh_CN part translation

### CODE REVIEW

**Review by stweil — APPROVED** [review]
Thank you for these improvements!

**Comment by stweil** [comment]
Your signature still looks strange. Did you set your real name for GitHub? It will be used for the list of contributors, but I don't thing that "bbbbtong" is a real name. Maybe you can still fix that.

**Comment by bbbbtong** [comment]
> Your signature still looks strange. Did you set your real name for GitHub? It will be used for the list of contributors, but I don't thing that "bbbbtong" is a real name. Maybe you can still fix that.

My name is Bo Tong. Sorry for misunderstanding.

**Comment by stweil** [comment]
You can update the signature in your local Git branch and then do a push with the "force" option to overwrite the old commit.

Your full name will be listed [here in the list of contributors](https://github.com/UB-Mannheim/PalMA/tree/master/locale#zh_cn).

**Comment by stweil** [comment]
Thank you. The changed translation is now part of the code.

**Pull request merged**
