### PR TITLE
Translated some untranslated sentences in Arabic

### PR DESCRIPTION
**Pull request by driad91**

### CODE REVIEW

**Comment by kba** [comment]
Thank you for the translations. before we can merge this, we need some formal changes:

Please [amend your commit](http://stackoverflow.com/questions/17647936/how-do-i-edit-an-incorrect-commit-message-with-tortoisegit) and add a ["Signed-Off" statement](https://tortoisegit.org/docs/tortoisegit/tgit-dug-commit.html). Then [force push](https://tortoisegit.org/docs/tortoisegit/tgit-dug-sync.html) your amended commit and we'll happily take it.

Also make sure, you have Git set up with name and email address.

Thank you for your contribution.

**Comment by stweil** [comment]
@driad91, I'd like to include your contribution in PalMA. Should we meet to finish the integration together, or do you want to update your pull request as suggested by @kba?

**Comment by stweil** [comment]
@driad91, ping.

**Comment by stweil** [comment]
@driad91, I'd still like to add your translations to PalMA. I can add a Signed-off-by comment to your commit message, but must know whether this is fine for you and which of your e-mail addresses should be used. Please either reply here or send me a personal e-mail. You may also close this pull request if you are no longer interested, of course.

**Comment by driad91** [comment]
Hi Stefan,

Sorry for the late reply...yes please feel free to use my translations and
use this email please

Thanks and best regards,
Daniel Riad

**Comment by stweil** [comment]
Thanks, these changes were pulled now.

**Pull request merged**
