### PR TITLE
Modified Italian directory

### PR DESCRIPTION
**Pull request by VaderSi**
Signed-off-by: srankl <srankl@mail.uni-mannheim.de>

### CODE REVIEW

**Review by stweil — CHANGES_REQUESTED** [review]
Thank you for these additional translations.

We publish the names of all contributors in https://github.com/UB-Mannheim/PalMA/blob/master/locale/README.md. You did not set your real name before preparing the commit, so you would not appear in that list. Many Open Source projects strictly require a real name for commits because that information is important for copyright and license tracking.

Do you want to fix the author name for your pull request (also in the Signed-off-by commit message)?

**Review by stweil — CHANGES_REQUESTED** [review]
Please update also the `Last-Translator` line.

**Comment by VaderSi** [comment]
Hello, 
sadly I don't know how to set my real name for the commit. Should I put it in the message box when committing or in the Read me File?

**Comment by stweil** [comment]
> I don't know how to set my real name for the commit.

In GitHub it can be set in your personal profile (https://github.com/settings/profile).
From the command line you can either edit `~/.gitconfig` or use `git config --global user.name "FIRSTNAME NAME"` and `git config --global user.email "YOUR_PREFERRED_EMAIL_ADDRESS` to set the name and the e-mail address.

The README file is generated from the commits, so it should not be edited manually.

**Comment by VaderSi** [comment]
Thank you for your help! I hope everything is now as expected. Have a nice weekend :)

**Pull request merged**
