### PR TITLE
Urdu Translation

### PR DESCRIPTION
**Pull request by takhan89**

### CODE REVIEW

**Comment by takhan89** [comment]
I have translated a few sentences into urdu

**Comment by kba** [comment]
:trophy: Great, thank you @takhan89!

To get this integrated into PalMA, we still need some adjustments. It's probably easiest, if you talk to @stweil, @zuphilip or me in person, so we can walk you through the necessary steps.

Thanks for contributing.

**Comment by kba** [comment]
Rebased and signed off, could be merged now. 

Still needs work on the Metadata though (we can do this). @takhan89 we would gladly merge any more urdu translations you provide.

**Comment by stweil** [comment]
@takhan89, thanks for the translation. It is now part of the PalMA code and will be activated on our PalMA stations in the next weeks. If you want to translate more lines, your pull request will be welcome.

**Pull request merged**
