### PR TITLE
Chinese version added

### PR DESCRIPTION
**Pull request by samuell3**

### CODE REVIEW

**Comment by stweil** [comment]
That's really great, many thanks. Could you please add one more line to your commit message:

    Signed-off-by: Caipei Song <csong@mail.uni-mannheim.de>

If you prefer, we could also add that signature for you. See http://elinux.org/Developer_Certificate_Of_Origin for more information on that process.

Kind regards,
Stefan

**Comment by samuell3** [comment]
Yeah you can add it for me[&#X1f60a]. I don't know a good way of changing commit message after a push.


Best,

Caipei

________________________________
Von: Stefan Weil <notifications@github.com>
Gesendet: Mittwoch, 20. Januar 2016 18:52
An: UB-Mannheim/PalMA
Cc: samuell3
Betreff: Re: [PalMA] Chinese version added (#16)


That's really great, many thanks. Could you please add one more line to your commit message:

Signed-off-by: Caipei Song <csong@mail.uni-mannheim.de>


If you prefer, we could also add that signature for you. See http://elinux.org/Developer_Certificate_Of_Origin for more information on that process.

Developer Certificate Of Origin - eLinux.org<http://elinux.org/Developer_Certificate_Of_Origin>
elinux.org
In May 2004, the kernel development community decided to standardize on a requirement to adhere to a Developer Certificate of Origin for contributions to the Linux ...



Kind regards,
Stefan

-

**Comment by stweil** [comment]
Pulled, thanks.

**Comment by zuphilip** [comment]
Cool! Thank you @samuell3 :tada:


Maybe interesting for another time:
<blockquote>I don't know a good way of changing commit message after a push.</blockquote>
 * work with feature branches, then you can `push --force` your changes also afterwards until the PR is accepted
 * changing commit message: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Pull request closed without merging**
